[package]
authors = ["Abdulsemiu Atanda <semiu@live.com>"]
name = "orchestra"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"

[[bin]]
name = "orchestra"
path = "src/main.rs"

[lib]
name="orchestra"
path="src/lib.rs"

[dependencies]
aws-config = "1.10.1"
aws-sdk-s3 = "1.141.0"
clap = { version = "4.6.6", features = ["derive", "env"] }
clap_derive = "4.6.4"
dialoguer = "0.12.0"
dotenvy = "0.15.7"
env_logger = "0.11.11"
log = "0.4.33"
network = { git = "https://github.com/abdulsemiu-atanda/network.git", rev = "920f6744669bd18aa179ae5910d872d6f963e43a" }
tokio = { version = "1.53.1", features = ["full"] }
